Feature/contact us
WSU-4110/Wayne-State-Blood-Bank pull request #49
Opened 2020-11-02 22:07 UTC by Kyle-WSU

2020-11-03 15:33 UTC, jacobboesch requested changes
For the most part everything looks good. 
However, you need to remove the commented code. 
Also, It looks like the Blood-Donatin.jpg file no longer exists on your branch. When I ran the program the image wasn't there.

2020-11-03 15:33 UTC, jacobboesch commented on src/main/resources/static/webpageFun.js
> +        //alert("You have been logged out.");
Remove commented out code

2020-11-03 15:33 UTC, jacobboesch commented on src/main/resources/static/webpageFun.js
> +      //alert("Only Administrators can access this page.");
Remove commented out code

2020-11-03 15:33 UTC, jacobboesch commented on src/main/resources/static/webpageFun.js
> +    //window.location.href= "index.html";
remove commented out code

2020-11-03 15:33 UTC, jacobboesch commented on src/main/resources/templates/accessDenied.html
> +    //alert("Only verified users can access this page. Please check your email.");
remove commented out code

2020-11-03 15:33 UTC, jacobboesch commented on src/main/resources/templates/accessDenied.html
> +    //alert("Only Administrators can access this page.");
Remove commented out code

2020-11-03 15:33 UTC, jacobboesch commented on src/main/resources/templates/viewFeedback.html
> +                            <!--<button class="ui red inverted button" id="temp" onclick="deleteButton(this.id)">Resolve</button>-->
remove this comment if it's not being used

2020-11-03 15:33 UTC, jacobboesch commented on src/main/resources/templates/viewFeedback.html
> +          //$("#temp").attr("id", data[i].id);
remove commented out code

2020-11-03 15:33 UTC, jacobboesch commented on src/main/resources/templates/viewFeedback.html
> +*/
remove this if it's not being used

2020-11-03 15:33 UTC, jacobboesch commented on src/main/resources/templates/viewFeedback.html
> +*/
Remove if not being used

2020-11-03 16:01 UTC, jacobboesch requested changes
The image folder still doesn't show up. Could you please add the Blood-Donation image back.

2020-11-03 17:46 UTC, jacobboesch approved these changes
Everything looks good 👍 . 
May want to change the email to a real admin email address when we eventually get one.

2020-11-03 20:54 UTC, Lloyd-Brombach-WSU approved these changes

2020-11-03 21:36 UTC, TheKPham approved these changes

2020-11-04 22:28 UTC, tia-gijo reviewed
good

2020-11-04 22:30 UTC, merged