Fix/navigation
WSU-4110/Wayne-State-Blood-Bank pull request #69
Opened 2020-11-23 19:14 UTC by Kyle-WSU

this makes it so that we only need to change the nav in one place

2020-11-23 21:48 UTC, jacobboesch requested changes
The following pages need to be updated with the new navigation code:
newsAndEvents.html
bloodDrives.html
addBloodDrive.html 

Also, requestBlood isn't on the navigation.

2020-11-24 14:28 UTC, jacobboesch approved these changes
It appears that there was a glitch with my IDE, the pages I requested the changes for don't exist on this branch. For the pages that are on this branch it works.

2020-11-27 20:56 UTC, Lloyd-Brombach-WSU approved these changes

2020-11-27 21:26 UTC, TheKPham approved these changes

2020-11-27 22:11 UTC, tia-gijo approved these changes

2020-11-27 22:37 UTC, merged